title: Agentic AI Tutorials
author: Your Name
copyright: "Â© 2024"

# Book settings
html:
  home_page_in_navbar: true
  baseurl: /

# Disable notebook execution
execute:
  execute_notebooks: "off"

# Jupyter Book settings
sphinx:
  config:
    html_theme_options:
      use_repository_button: false
      use_edit_page_button: false
    mystnb:
      extract_attachments: True
      extract_outputs: True
